---
- name: Upload artifact to server, unpack, prepare and set valid link
  become: yes
  become_user: www-data
  hosts: "{{ deployhosts }}"
  vars:
    project_root: "/var/www/hireinsocial"
    project_upload: "{{ project_root }}/master"
    current_path: "{{ project_root }}/current"
    release_path: "{{ project_upload }}/{{ deploy_directory }}"
    log_path: "/var/log/{{ deployhosts }}"

  tasks:
    - name: Register timestamp variable
      shell: date +%Y_%m_%d_%H_%M_%S
      register: timestamp

    - name: Register deployment directory from stdout
      set_fact: "deploy_directory={{ timestamp.stdout }}"

    - name: Debugging deployment directory
      debug:
        msg: "Deployment directory: {{ deploy_directory }}"

    - name: Create project root path
      become: yes
      become_user: root
      file:
        state: directory
        path: "{{ project_root }}"
        owner: www-data
        group: www-data

    - name: Create upload folder
      file:
        state: directory
        path: "{{ project_upload }}"
        owner: www-data
        group: www-data

    - name: Create artifact folder for PHP
      file:
        state: directory
        path: "{{ release_path }}"
        owner: www-data
        group: www-data
      when: release_path is defined

    - name: Upload and unpack artifact
      unarchive:
        src: "{{ artefact_path }}"
        dest: "{{ release_path }}"

    - name: Change uploaded folder group
      file:
        path: "{{ release_path }}"
        state: directory
        group: www-data
        mode: 0775
        recurse: yes

    - name: Create directory for log files
      become: yes
      become_user: root
      file:
        state: directory
        path: "{{ log_path }}"
        owner: www-data
        group: www-data

    - name: Warmup symfony cache
      shell: php {{ release_path }}/bin/symfony ca:wa --env=prod

    - name: Execute migrations
      shell: php {{ release_path }}/bin/db migrations:migrate -n
      register: migrations

    - name: Migrations - stdout
      debug: msg="{{ migrations.stdout }}"

    - name: Migrations - stderr
      debug: msg="{{ migrations.stderr }}"

    - name: Remove link to old application code
      file:
        path: "{{ current_path }}"
        state: absent

    - name: Create link to shiny new application
      file:
        src: "{{ project_upload }}/{{ deploy_directory }}"
        dest: "{{ current_path }}"
        state: link

    - name: Restart FPM
      become: yes
      become_user: root
      service:
        name: php7.2-fpm
        state: restarted

    - name: Register variable with all uploaded archives
      shell: ls
      register: artifacts
      args:
        chdir: "{{ project_upload }}"

    - name: Delete old builds
      file:
        name: "{{ project_upload }}/{{ item }}"
        state: absent
      with_items: "{{ artifacts.stdout_lines | default([]) }}"
      when: item != deploy_directory
      ignore_errors: yes
